### ISSUE TITLE
Landscape-x主题疑惑

### ISSUE THREAD

**Issue by Orzsxy** [HipHopCoderS/Landscape-x#1]
使用这个主题过程中遇到了一些解决不了的问题求指点啊、、、
1、把主题文件下的 _config.yml 替换hexo 项目下的 _config.yml，开始对这句话理解成：主题文件下的_config.yml文件用hexo目录下的_config.yml替换（理解反了）
2、先配置下个人的CDN ,博客中的图片引用都是通过CDN地址的, 使用中只用填写cdn 上的文件名即可，例如qq,weixin 图片的引用# img CDN path   cdn-url: you cdn path
自己都不知道这是写的什么意思，，，不清楚怎样配置cdn
3、部署到本地之后用浏览器检查功能检查出来了出现4个错误
其中一个在删除hexo文件下_config.yml文件中disqus_shortname:   后面的部分可以得到解决
另外三个是：是连接模块的图片加载不出来，不知道怎么解决了,,,,,，，，
4、知道了后期对一些个人信息设置都是在hexo下的_config.yml文件进行操作，可是没学过里面的内容是什么意思，无法做出修改。
求指点、、、、

**Comment by HipHopCoderS** [comment]
这几个问题我看到了，我都给你回复下吧 ，有什么问题 我总结下 
1. 你需要的应该是 图片的显示，还有博文的自定义
2. 还有各种配置参数的理解  应该是这样的对吧

**Comment by Orzsxy** [comment]
嗯嗯，是这样的，有时间能写一些教程嘛

**Comment by HipHopCoderS** [comment]
主题新版已经更新，欢迎体验，有问题继续优化，谢谢！
